id: P49532218
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG6169
  instance_id: http://purl.bdrc.io/resource/IE1KG6169
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དཔའ་རིས་བསང་བརྔན་ཡིད་བཞིན་འགུགས་པའི་ལྕགས་ཀྱུ།
  alt_title:
    en-x-mixed:
    - Dpaʼ-ris bsaṅ brṅon yid bźin ʼgugs paʼi lcags kyu /[ʼJa-mo Gnas-brtan-tshe-riṅ
      sogs kyis sdud sgrig byas].
    zh-latn-pinyin-x-ndia:
    - hua rui shan shen song
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    2a4f92b870fc4f7aa62af687c3476605:
      title: པོད ༡་དཔའ་རིས་བསང་བརྔན་ཡིད་བཞིན་འགུགས་པའི་ལྕགས་ཀྱུ།
      volume_number: 1
      base_file: UT1KG6169_I1KG9320_0000.txt
      reference: http://purl.bdrc.io/resource/VL92746CE3B0932DAB
      image_group: I1KG9320
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG6169
  - http://purl.bdrc.io/resource/W1KG6169
  ocr_software: Namsel
created_at: '2021-12-22T10:57:22.762114'
last_modified_at: '2021-12-22T10:57:22.762121'
statistics:
  total_words: 106580
  total_non_words: 14517
quality:
  non_words_ratio: 0.14
